<?php
$title = 'Mes articles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('articles', array('action' => 'add')); ?>">
        Ajouter un article</a>
</p>
<table class="table">
    <tr>
        <th>Nom</th>
        <th>Référence</th>
        <th>Stock actuel</th>
        <th>Stock minimum</th>
        <th>Prix</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($articles as $article) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($article->articles_nom); ?></td>
        <td><?php echo $this->escapeHtml($article->articles_ref) ?></td>
        <td><?php echo $article->articles_stock; ?></td>
        <td><?php echo $article->articles_min; ?></td>
        <td><?php echo $article->articles_prix; ?></td>
        <td>
            <a href="<?php
            echo $this->url('articles', array('action' => 'edit', 'id' => $article->articles_id));
            ?>">Modifier</a>
            <a href="<?php
            echo $this->url('articles', array('action' => 'delete',
                'id' => $article->articles_id));
            ?>">Supprimer</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>


